import type { Application } from "./types";

export const demoApplications: Application[] = [
  {
    id: "app-demo-1",
    created_at: "2026-07-06T09:20:00.000Z",
    updated_at: null,
    full_name: "Neha Kulkarni",
    date_of_birth: "2003-02-14",
    gender: "Female",
    mobile_number: "9876543210",
    email: "neha@example.com",
    current_city: "Pune",
    current_state: "Maharashtra",
    applying_as: "volunteer",
    current_status: "Student",
    organization_name: "Fergusson College",
    preferred_start_date: "2026-07-15",
    preferred_end_date: "2026-09-15",
    expected_duration: "2 Months",
    availability: "Weekends",
    hours_per_week: 6,
    preferred_mode: "Offline",
    areas_of_interest: ["Student Teaching", "School Painting"],
    hear_about: "Instagram",
    reference_name: null,
    resume_url: null,
    linkedin_profile: "https://linkedin.com/in/neha-demo",
    emergency_contact_name: "Anita Kulkarni",
    emergency_contact_relationship: "Mother",
    emergency_contact_mobile: "9876500000",
    declaration_accuracy: true,
    declaration_unpaid: true,
    declaration_safeguarding: true,
    declaration_code_of_conduct: true,
    declaration_media_consent: true,
    status: "Pending",
    user_id: null,
    admin_notes: null,
    reviewed_at: null,
    reviewed_by: null
  },
  {
    id: "app-demo-2",
    created_at: "2026-07-05T13:10:00.000Z",
    updated_at: "2026-07-07T10:00:00.000Z",
    full_name: "Arjun Rao",
    date_of_birth: "2001-10-03",
    gender: "Male",
    mobile_number: "9000012345",
    email: "arjun@example.com",
    current_city: "Mumbai",
    current_state: "Maharashtra",
    applying_as: "intern",
    current_status: "Student",
    organization_name: "Mumbai University",
    preferred_start_date: "2026-08-01",
    preferred_end_date: "2026-11-01",
    expected_duration: "3 Months",
    availability: "Weekdays",
    hours_per_week: 12,
    preferred_mode: "Hybrid",
    areas_of_interest: ["Dashboard Development", "Data Analysis"],
    hear_about: "College",
    reference_name: "Prof. Mehta",
    resume_url: null,
    linkedin_profile: null,
    emergency_contact_name: "Suresh Rao",
    emergency_contact_relationship: "Father",
    emergency_contact_mobile: "9000099999",
    declaration_accuracy: true,
    declaration_unpaid: true,
    declaration_safeguarding: true,
    declaration_code_of_conduct: true,
    declaration_media_consent: true,
    status: "Approved",
    user_id: "TSF0001",
    admin_notes: "Strong dashboard experience.",
    reviewed_at: "2026-07-07T10:00:00.000Z",
    reviewed_by: "Admin"
  },
  {
    id: "app-demo-3",
    created_at: "2026-07-04T16:45:00.000Z",
    updated_at: "2026-07-06T08:15:00.000Z",
    full_name: "Vikas Sharma",
    date_of_birth: "1998-05-22",
    gender: "Male",
    mobile_number: "9111111111",
    email: "vikas@example.com",
    current_city: "Delhi",
    current_state: "Delhi",
    applying_as: "volunteer",
    current_status: "Working Professional",
    organization_name: "Independent",
    preferred_start_date: "2026-07-20",
    preferred_end_date: "2026-08-20",
    expected_duration: "1 Month",
    availability: "Flexible",
    hours_per_week: 3,
    preferred_mode: "Remote",
    areas_of_interest: ["Fundraising"],
    hear_about: "LinkedIn",
    reference_name: null,
    resume_url: null,
    linkedin_profile: "https://linkedin.com/in/vikas-demo",
    emergency_contact_name: "Kavita Sharma",
    emergency_contact_relationship: "Sister",
    emergency_contact_mobile: "9222222222",
    declaration_accuracy: true,
    declaration_unpaid: true,
    declaration_safeguarding: true,
    declaration_code_of_conduct: true,
    declaration_media_consent: true,
    status: "Rejected",
    user_id: null,
    admin_notes: "Availability does not match current field requirement.",
    reviewed_at: "2026-07-06T08:15:00.000Z",
    reviewed_by: "Admin"
  }
];
