import type { Activity, VolunteerApplication } from "./types";

export const demoActivities: Activity[] = [
  {
    id: "demo-1",
    created_at: "2026-01-12T10:00:00.000Z",
    user_id: null,
    auth_user_id: null,
    activity_date: "2026-01-12",
    volunteer_name: "Aarav Shah",
    entry_type: "volunteer",
    volunteer_type: "Individual Volunteer",
    organisation: "Independent",
    location: "Pune",
    programme_name: "STEM Learning",
    project_type: "Student Teaching",
    num_volunteers: 1,
    volunteering_hours: 4,
    beneficiaries_impacted: 45,
    trees_planted: 0,
    activities_completed: null,
    remarks: "Introductory STEM session",
    submitted_by: "Staff",
    department: null,
    intern_work_type: null,
    supervisor_name: null,
    milestone: null,
    internship_hours: null,
    deliverables_completed: null,
    internship_start_date: null,
    internship_end_date: null,
    staff_in_charge: "Santosh Phad"
  },
  {
    id: "demo-2",
    created_at: "2026-02-18T10:00:00.000Z",
    user_id: null,
    auth_user_id: null,
    activity_date: "2026-02-18",
    volunteer_name: "Meera Iyer",
    entry_type: "intern",
    volunteer_type: null,
    organisation: "Symbiosis College",
    location: "Mumbai",
    programme_name: null,
    project_type: null,
    num_volunteers: null,
    volunteering_hours: null,
    beneficiaries_impacted: 120,
    trees_planted: null,
    activities_completed: null,
    remarks: "Catalogued books and setup shelves",
    submitted_by: "Self",
    department: "Design",
    intern_work_type: "Documentation",
    supervisor_name: "Sneha G.",
    milestone: "Library Access cataloging & setup",
    internship_hours: 18,
    deliverables_completed: 2,
    internship_start_date: "2026-01-05",
    internship_end_date: "2026-04-05",
    staff_in_charge: "ThinkSharp Foundation Staff"
  },
  {
    id: "demo-3",
    created_at: "2026-03-22T10:00:00.000Z",
    user_id: null,
    auth_user_id: null,
    activity_date: "2026-03-22",
    volunteer_name: "GreenWorks Team",
    entry_type: "volunteer",
    volunteer_type: "Corporate Volunteer",
    organisation: "GreenWorks",
    location: "Nashik",
    programme_name: "Environment",
    project_type: "Plantation Drive",
    num_volunteers: 14,
    volunteering_hours: 56,
    beneficiaries_impacted: 80,
    trees_planted: 210,
    activities_completed: null,
    remarks: "School campus plantation",
    submitted_by: "Staff",
    department: null,
    intern_work_type: null,
    supervisor_name: null,
    milestone: null,
    internship_hours: null,
    deliverables_completed: null,
    internship_start_date: null,
    internship_end_date: null,
    staff_in_charge: "Santosh Phad"
  },
  {
    id: "demo-4",
    created_at: "2026-04-07T10:00:00.000Z",
    user_id: null,
    auth_user_id: null,
    activity_date: "2026-04-07",
    volunteer_name: "Riya Menon",
    entry_type: "intern",
    volunteer_type: null,
    organisation: "Fergusson College",
    location: "Pune",
    programme_name: null,
    project_type: null,
    num_volunteers: null,
    volunteering_hours: null,
    beneficiaries_impacted: 64,
    trees_planted: null,
    activities_completed: null,
    remarks: null,
    submitted_by: "Self",
    department: "Tech",
    intern_work_type: "Dashboard Development",
    supervisor_name: "Rohan D.",
    milestone: "Digital Literacy labs configuration",
    internship_hours: 24,
    deliverables_completed: 4,
    internship_start_date: "2026-02-15",
    internship_end_date: "2026-05-15",
    staff_in_charge: "ThinkSharp Fellow"
  }
];

export const demoApplications: VolunteerApplication[] = [
  {
    id: "app-1",
    created_at: "2026-07-01T12:00:00.000Z",
    full_name: "Rahul Verma",
    date_of_birth: "2002-05-14",
    gender: "Male",
    mobile_number: "+91 98765 43210",
    email: "rahul.verma@example.com",
    current_city: "Pune",
    current_state: "Maharashtra",
    applying_as: "volunteer",
    current_status: "Student",
    organization_name: "COEP Tech University",
    preferred_start_date: "2026-08-01",
    preferred_end_date: "2026-09-01",
    expected_duration: "1 Month",
    availability: "Flexible",
    hours_per_week: 15,
    preferred_mode: "Hybrid",
    area_of_interest: "Student Teaching, School Painting",
    referral_source: "Social Media",
    reference_name: "Prof. S. Joshi",
    resume_url: "https://example.com/resumes/rahul_verma.pdf",
    linkedin_profile: "https://linkedin.com/in/rahulverma",
    emergency_contact_name: "Anil Verma",
    emergency_relationship: "Father",
    emergency_mobile: "+91 98765 43211",
    declaration_accepted: true,
    status: "Pending"
  },
  {
    id: "app-2",
    created_at: "2026-07-02T10:30:00.000Z",
    full_name: "Sneha Patil",
    date_of_birth: "2000-09-22",
    gender: "Female",
    mobile_number: "+91 98123 45678",
    email: "sneha.patil@example.com",
    current_city: "Mumbai",
    current_state: "Maharashtra",
    applying_as: "intern",
    current_status: "Working Professional",
    organization_name: "TechCorp Solutions",
    preferred_start_date: "2026-08-15",
    preferred_end_date: "2026-11-15",
    expected_duration: "3 Months",
    availability: "Weekends",
    hours_per_week: 10,
    preferred_mode: "Remote",
    area_of_interest: "AI Project, Data Analysis",
    referral_source: "Friend",
    reference_name: "Riya Patil",
    resume_url: null,
    linkedin_profile: "https://linkedin.com/in/snehapatil",
    emergency_contact_name: "Meera Patil",
    emergency_relationship: "Mother",
    emergency_mobile: "+91 98123 45679",
    declaration_accepted: true,
    status: "Approved"
  }
];
